export default [
  {
    text: "HTML / CSS",
    collapsed: true,
    items: [
      { text: "HTML", link: "/fe/html/html" },
      { text: "HTML5", link: "/fe/html/html5" },
      { text: "CSS", link: "/fe/css/css" },
      { text: "Flex", link: "/fe/css/flex" },
      { text: "Grid", link: "/fe/css/grid" },
      { text: "Less", link: "/fe/css/less" },
      { text: "Sass", link: "/fe/css/Sass详解" },
    ],
  },
  {
    text: "JavaScript",
    collapsed: true,
    items: [
      { text: "JS 简介", link: "/fe/js/what_is_js" },
      { text: "JS 数组", link: "/fe/js/array" },
      { text: "Web Storage 浏览器本地存储", link: "/fe/js/webstorage" },
      { text: "JS 模块化", link: "/fe/js/js_modules" },
      { text: "ES6常用知识", link: "/fe/js/ES6常用知识" },
      { text: "array", link: "/fe/js/array" },
      { text: "json-server", link: "/fe/js/json-server" },
    ],
  },
  {
    text: "Vue",
    collapsed: true,
    items: [
      { text: "Vue 核心基础", link: "/fe/vue/vue_core_basis" },
      { text: "Vue 组件化编程", link: "/fe/vue/vue_component_coding" },
      { text: "Vue 组件进阶", link: "/fe/vue/vue_component_advanced" },
      { text: "Vue 脚手架", link: "/fe/vue/vue_cli" },
      { text: "Vue 网络请求", link: "/fe/vue/vue_network_request" },
      { text: "Vuex", link: "/fe/vue/vuex" },
      { text: "Vue Router", link: "/fe/vue/vue_router" },
      { text: "Vue3", link: "/fe/vue/vue3" },
      { text: "Vue3项目配置", link: "/fe/vue/Vue3项目配置" },
      { text: "Vue3学习(新)", link: "/fe/vue/Vue3学习(新)" },
      { text: "vue组件之间传递数据", link: "/fe/vue/vue组件之间传递数据" },
      {
        text: "Vue 封装API",
        link: "/fe/vue/使用 Vue3 封装一些有用的组合 API",
      },
      { text: "Vue3学习(新)", link: "/fe/vue/Vue3学习(新)" },
    ],
  },
  {
    text: "Nodejs",
    collapsed: true,
    items: [
      { text: "Nodejs 基础", link: "/fe/nodejs/node_basis" },
      { text: "Express", link: "/fe/nodejs/express" },
      { text: "数据库和身份认证", link: "/fe/nodejs/mysql" },
      { text: "大事件后台 API 项目", link: "/fe/nodejs/ev_api_server" },
    ],
  },
  {
    text: "Other",
    collapsed: true,
    items: [
      { text: "Webpack", link: "/fe/webpack/webpack_basis" },
      { text: "Vscode", link: "/fe/ide/vscode" },
      { text: "Vuepress", link: "/fe/vuepress/vuepress" },
      { text: "Vitepress", link: "/fe/vuepress/vitepress" },
      { text: "前端编程题", link: "/fe/js/coding_problem" },
    ],
  },
];
